#!/usr/bin/python2.5

application: checkout-dialog
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /zipme
  script: zipme.py
  login: admin

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: /images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /static
  static_dir: static

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /codemirror
  static_dir: codemirror

- url: .*
  script: main.py
